package o1.subprograms

import scala.math.max

// Here are some example functions whose implementations we examine
// in Chapter 1.8. See the chapter text for detailed explanations.

// DO NOT EDIT THIS FILE. There’s only example code here.
// The code that you’ll write for the programming assignments
// goes in the other files named after "week1" and "week2".

def greatestDistance(x1: Double, y1: Double, x2: Double, y2: Double, x3: Double, y3: Double) =
  val first  = distance(x1, y1, x2, y2)
  val second = distance(x1, y1, x3, y3)
  val third  = distance(x2, y2, x3, y3)
  max(max(first, second), third)


def test1(text: String) =
  println(text)
  "always the same string"

def test2(text: String) =
  println(text)
  val response = test1(yell(text))
  test1(text)
  println("we got:")
  println(response)


def yell(phrase: String) = phrase + "!"


